### PR TITLE
Init tests and Jenkinsfile

### PR DESCRIPTION
**Pull request by Vadimkin**
Here is initial jenkinsfile with tests:
https://jenkins.authentise.com/blue/organizations/jenkins/pack3d/detail/jenkinsfile/8/pipeline/13/

One thing: output of `bin/pack3d 20 40 30 2.0 pack3d_transforms 1 tests/stl/logo.stl` is always different. but file the same. Is there are any way to check packer?

Clubhouse task:
[ch1110](https://app.clubhouse.io/authentise/story/1110/pack3d-compiled-tested-on-jenkins)

### CODE REVIEW

**Comment by Minglunt** [comment]
Yes, for the same input, `pack3d` can give different outputs. Because it packs input models randomly, as long as the output can be in the build volume.

**Comment by Vadimkin** [comment]
Ok, removed fixtures.

Jenkins now will check only exit status of this binary file

**Review by far-authentise — APPROVED** [review]
Thanks. Looking forward to getting a standard way to build this before Minglun finish his internship

**Review by Minglunt — APPROVED** [review]
Looks good to me too.

**Pull request merged**
